a:205:{i:0;a:3:{i:0;s:14:"document_start";i:1;a:0:{}i:2;i:0;}i:1;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:28:"Test Scripts in BioCatalogue";i:1;i:2;i:2;i:1;}i:2;i:1;}i:2;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:2;}i:2;i:1;}i:3;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:42;}i:4;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:22:"What Are Test Scripts?";i:1;i:3;i:2;i:42;}i:2;i:42;}i:5;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:3;}i:2;i:42;}i:6;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:42;}i:7;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:175:"Test scripts are simple clients to web services which can be uploaded to the BioCatalogue to be run by the BioCatalogue system. The purpose of the test scripts is double fold:";}i:2;i:76;}i:8;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:251;}i:9;a:3:{i:0;s:10:"listu_open";i:1;a:0:{}i:2;i:251;}i:10;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:251;}i:11;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:251;}i:12;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:73:" they provide the users  with an example client of how to use the service";}i:2;i:255;}i:13;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:328;}i:14;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:328;}i:15;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:328;}i:16;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:328;}i:17;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:115:" they enable the biocatalogue system to monitor the status of the service by running these sample clients regularly";}i:2;i:332;}i:18;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:447;}i:19;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:447;}i:20;a:3:{i:0;s:11:"listu_close";i:1;a:0:{}i:2;i:447;}i:21;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:449;}i:22;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:29:"Who Can Submit a Test Script?";i:1;i:3;i:2;i:449;}i:2;i:449;}i:23;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:3;}i:2;i:449;}i:24;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:449;}i:25;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:313:"Only those that have full permissions on services to BioCatalogue are able to submit test scripts as well. They can only submit test scripts against the services which they registered or are responsible for. You can check your user profile on BioCatalogue to see the services you submitted or are responsible for.";}i:2;i:490;}i:26;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:803;}i:27;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:805;}i:28;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:34:"What Kinds of Scripts are Allowed?";i:1;i:3;i:2;i:805;}i:2;i:805;}i:29;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:3;}i:2;i:805;}i:30;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:805;}i:31;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:74:"Test script should be written in one of the following scripting languages:";}i:2;i:851;}i:32;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:925;}i:33;a:3:{i:0;s:10:"listu_open";i:1;a:0:{}i:2;i:925;}i:34;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:925;}i:35;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:925;}i:36;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:5:" perl";}i:2;i:929;}i:37;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:934;}i:38;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:934;}i:39;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:934;}i:40;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:934;}i:41;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:7:" python";}i:2;i:938;}i:42;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:945;}i:43;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:945;}i:44;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:945;}i:45;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:945;}i:46;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:5:" ruby";}i:2;i:949;}i:47;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:954;}i:48;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:954;}i:49;a:3:{i:0;s:11:"listu_close";i:1;a:0:{}i:2;i:954;}i:50;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:954;}i:51;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:33:"BioCatalogue is also able to run ";}i:2;i:956;}i:52;a:3:{i:0;s:12:"externallink";i:1;a:2:{i:0;s:22:"http://www.soapui.org/";i:1;s:6:"soapUI";}i:2;i:989;}i:53;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:90:" project files. These are xml files that can be generated by building test cases with the ";}i:2;i:1022;}i:54;a:3:{i:0;s:12:"externallink";i:1;a:2:{i:0;s:22:"http://www.soapui.org/";i:1;s:6:"soapUI";}i:2;i:1112;}i:55;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:11:" framework.";}i:2;i:1145;}i:56;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:1157;}i:57;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:1157;}i:58;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:46:"What is the Specification of the Test Scripts?";i:1;i:3;i:2;i:1157;}i:2;i:1157;}i:59;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:3;}i:2;i:1157;}i:60;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:1157;}i:61;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:50:"Test scripts should have the following properties:";}i:2;i:1215;}i:62;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:1265;}i:63;a:3:{i:0;s:10:"listu_open";i:1;a:0:{}i:2;i:1265;}i:64;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:1265;}i:65;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:1265;}i:66;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:89:" Test script files should be executable on the command line and should take no arguments.";}i:2;i:1269;}i:67;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:1358;}i:68;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:1358;}i:69;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:1358;}i:70;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:1358;}i:71;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:21:" Test scripts should ";}i:2;i:1362;}i:72;a:3:{i:0;s:11:"strong_open";i:1;a:0:{}i:2;i:1383;}i:73;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:6:"always";}i:2;i:1385;}i:74;a:3:{i:0;s:12:"strong_close";i:1;a:0:{}i:2;i:1391;}i:75;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:169:" exit with a status code which determines whether the test passed or not.  This code is an integer between 0 and 255 (inclusive) where 0 indicates successful execution. ";}i:2;i:1393;}i:76;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:1562;}i:77;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:1562;}i:78;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:1562;}i:79;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:1562;}i:80;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:118:" If a script requires other files, these files should supplied with the script. These can be uploaded as a zip archive";}i:2;i:1566;}i:81;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:1684;}i:82;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:1684;}i:83;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:1684;}i:84;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:1684;}i:85;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:122:" Execution time for script should not be more than an hour. Script will be terminated if they exceed this max allowed time";}i:2;i:1688;}i:86;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:1810;}i:87;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:1810;}i:88;a:3:{i:0;s:11:"listu_close";i:1;a:0:{}i:2;i:1810;}i:89;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:1813;}i:90;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:66:"Will Scripts be available for running immediately upon Submission?";i:1;i:3;i:2;i:1813;}i:2;i:1813;}i:91;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:3;}i:2;i:1813;}i:92;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:1813;}i:93;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:249:" Yes. However, newly submitted scripts will be  schedule for the next run of the monitoring framework. The BioCatalogue administrators however reserve the right to deactivate any tests if they are deemed to be unsuitable for the monitoring purpose. ";}i:2;i:1891;}i:94;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:2141;}i:95;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:2141;}i:96;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:42:"Which libraries does BioCatalogue Support?";i:1;i:3;i:2;i:2141;}i:2;i:2141;}i:97;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:3;}i:2;i:2141;}i:98;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:2141;}i:99;a:3:{i:0;s:11:"strong_open";i:1;a:0:{}i:2;i:2195;}i:100;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:4:"Perl";}i:2;i:2197;}i:101;a:3:{i:0;s:12:"strong_close";i:1;a:0:{}i:2;i:2201;}i:102;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:2203;}i:103;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:2203;}i:104;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:50:"The main module needed for WSDL services include :";}i:2;i:2205;}i:105;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:2256;}i:106;a:3:{i:0;s:10:"listu_open";i:1;a:0:{}i:2;i:2256;}i:107;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2256;}i:108;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2256;}i:109;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:12:" XML::LibXML";}i:2;i:2260;}i:110;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2272;}i:111;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2272;}i:112;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2272;}i:113;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2272;}i:114;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:26:" XML::Compile version 1.07";}i:2;i:2276;}i:115;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2302;}i:116;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2302;}i:117;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2302;}i:118;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2302;}i:119;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:34:" XML::Compile::WSDL11 version 2.08";}i:2;i:2306;}i:120;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2340;}i:121;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2340;}i:122;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2340;}i:123;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2340;}i:124;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:34:" XML::Compile::SOAP11 version 2.08";}i:2;i:2344;}i:125;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2378;}i:126;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2378;}i:127;a:3:{i:0;s:11:"listu_close";i:1;a:0:{}i:2;i:2378;}i:128;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:2378;}i:129;a:3:{i:0;s:11:"strong_open";i:1;a:0:{}i:2;i:2380;}i:130;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:6:"Python";}i:2;i:2382;}i:131;a:3:{i:0;s:12:"strong_close";i:1;a:0:{}i:2;i:2388;}i:132;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:0:"";}i:2;i:2390;}i:133;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:2391;}i:134;a:3:{i:0;s:10:"listu_open";i:1;a:0:{}i:2;i:2391;}i:135;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2391;}i:136;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2391;}i:137;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:20:" PyXML version 0.8.4";}i:2;i:2395;}i:138;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2415;}i:139;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2415;}i:140;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2415;}i:141;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2415;}i:142;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:22:" fpconst version 0.7.2";}i:2;i:2419;}i:143;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2441;}i:144;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2441;}i:145;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2441;}i:146;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2441;}i:147;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:16:" ZSI version 2.1";}i:2;i:2445;}i:148;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2461;}i:149;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2461;}i:150;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2461;}i:151;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2461;}i:152;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:22:" SOAPpy version 0.12.0";}i:2;i:2465;}i:153;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2487;}i:154;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2487;}i:155;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2487;}i:156;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2487;}i:157;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:8:" MySQLdb";}i:2;i:2491;}i:158;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2499;}i:159;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2499;}i:160;a:3:{i:0;s:11:"listu_close";i:1;a:0:{}i:2;i:2499;}i:161;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:2499;}i:162;a:3:{i:0;s:11:"strong_open";i:1;a:0:{}i:2;i:2501;}i:163;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:4:"Ruby";}i:2;i:2503;}i:164;a:3:{i:0;s:12:"strong_close";i:1;a:0:{}i:2;i:2507;}i:165;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:0:"";}i:2;i:2509;}i:166;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:2510;}i:167;a:3:{i:0;s:10:"listu_open";i:1;a:0:{}i:2;i:2510;}i:168;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:2510;}i:169;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:2510;}i:170;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:19:" ruby version 1.8.6";}i:2;i:2514;}i:171;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:2533;}i:172;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:2533;}i:173;a:3:{i:0;s:11:"listu_close";i:1;a:0:{}i:2;i:2533;}i:174;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:2535;}i:175;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:7:"Example";i:1;i:3;i:2;i:2535;}i:2;i:2535;}i:176;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:3;}i:2;i:2535;}i:177;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:2554;}i:178;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:4:"Perl";i:1;i:4;i:2;i:2554;}i:2;i:2554;}i:179;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:4;}i:2;i:2554;}i:180;a:3:{i:0;s:6:"p_open";i:1;a:0:{}i:2;i:2554;}i:181;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:27:"Sample perl client for the ";}i:2;i:2568;}i:182;a:3:{i:0;s:12:"externallink";i:1;a:2:{i:0;s:40:"http://www.biocatalogue.org/services/106";i:1;s:16:"EMBOSS showfeat ";}i:2;i:2595;}i:183;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:26:" service in BioCatalogue. ";}i:2;i:2656;}i:184;a:3:{i:0;s:7:"p_close";i:1;a:0:{}i:2;i:2682;}i:185;a:3:{i:0;s:4:"code";i:1;a:3:{i:0;s:1833:"

#!/usr/bin/perl

use XML::Compile::SOAP11;
use XML::Compile::WSDL11;
use XML::Compile::Transport::SOAPHTTP;
use strict;

####

eval {

	my $inputs = {
		'sequence' => { 'usa' => 'embl:X65921'}
	};

	my $serviceendpoint =
	  'http://www.ebi.ac.uk/soaplab/typed/services/display.showfeat';

	print "Retriving and processing the WSDL and the XSDs imported\n";
	my $wsdl  = XML::LibXML->new->parse_file( $serviceendpoint . '?wsdl' );
	my $proxy = XML::Compile::WSDL11->new($wsdl);
	foreach my $schema ( 1, 2, 3 ) {
		my $xsdXml =
		  XML::LibXML->new->parse_file( $serviceendpoint . '?xsd=' . $schema );
		if($XML::Compile::SOAP::VERSION < 2.0)
		{
			$proxy->schemas->importDefinitions($xsdXml);
		}
		else
		{
			$proxy->importDefinitions($xsdXml);
		}
	}

	print "Preparing caller object for runAndWaitFor operation\n";
	my $runAndWaitFor = $proxy->compileClient('runAndWaitFor');

	print "Calling the service and getting the response\n";
	my ( $answer, $trace ) = $runAndWaitFor->( $inputs );

	# &printTrace($trace);

	my %answer = %{$answer};
	my %answer_ = %{ $answer{'runAndWaitForResponse'} };
	my $report = $answer_{'report'};
	my $detailed_status = $answer_{'detailed_status'};
	my $outfile = $answer_{'outfile'};
	my $outfile_url = $answer_{'outfile_url'};


	print "\nSoaplab report received:\n----------------------------\n\n$report\n";

	if ( $detailed_status == 0 ) {
		print "Passed\n";
		exit 0;
	}

	print "Failed\n";
	exit 1;
};

if ($@) {
	print "Caught an exception\n" . $@;
	exit 1;
}

# Print request/response trace
sub printTrace($) {
	my $trace = shift;
	$trace->printTimings;
	$trace->printRequest;
	$trace->printResponse;
}

# File to String
sub file2String($) {
	my $fname = shift;
	open FILE, $fname or die "Couldn't open file: $!";
	my $fcontent = join( "", <FILE> );
	close FILE;
	return $fcontent;
}


";i:1;N;i:2;N;}i:2;i:2689;}i:186;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:4533;}i:187;a:3:{i:0;s:6:"header";i:1;a:3:{i:0;s:10:"References";i:1;i:3;i:2;i:4533;}i:2;i:4533;}i:188;a:3:{i:0;s:12:"section_open";i:1;a:1:{i:0;i:3;}i:2;i:4533;}i:189;a:3:{i:0;s:10:"listu_open";i:1;a:0:{}i:2;i:4554;}i:190;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:4554;}i:191;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:4554;}i:192;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:1:" ";}i:2;i:4558;}i:193;a:3:{i:0;s:12:"externallink";i:1;a:2:{i:0;s:44:"http://www.embraceregistry.net/documentation";i:1;s:30:"Embrace Registry Documentation";}i:2;i:4559;}i:194;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:4638;}i:195;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:4638;}i:196;a:3:{i:0;s:13:"listitem_open";i:1;a:1:{i:0;i:1;}i:2;i:4638;}i:197;a:3:{i:0;s:16:"listcontent_open";i:1;a:0:{}i:2;i:4638;}i:198;a:3:{i:0;s:5:"cdata";i:1;a:1:{i:0;s:1:" ";}i:2;i:4642;}i:199;a:3:{i:0;s:12:"externallink";i:1;a:2:{i:0;s:22:"http://www.soapui.org/";i:1;s:37:"soapUI Web Services Testing Framework";}i:2;i:4643;}i:200;a:3:{i:0;s:17:"listcontent_close";i:1;a:0:{}i:2;i:4707;}i:201;a:3:{i:0;s:14:"listitem_close";i:1;a:0:{}i:2;i:4707;}i:202;a:3:{i:0;s:11:"listu_close";i:1;a:0:{}i:2;i:4707;}i:203;a:3:{i:0;s:13:"section_close";i:1;a:0:{}i:2;i:4708;}i:204;a:3:{i:0;s:12:"document_end";i:1;a:0:{}i:2;i:4708;}}