# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 03 Jun 2008 10:07:24 +0100
*	@ALL	0
*	@user	8
*	@visitors	1
development:*	@ALL	1
development:*	@user	8
development:handover_2011	@ALL	0
development:handover_2011	@user	2
development:pilot_dev_notes	jits	2
development:pilot_dev_notes	@ALL	0
development:pilot_dev_notes	tlaurent	2
development:pilot_dev_notes	rhaines	2
development:release_notes	@ALL	1
home	@ALL	1
home	@user	2
meetings:emory_2011-01-10	@ALL	1
public	@ALL	1
public	@user	2
public:*	@ALL	1
public:*	@user	8
