<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: alex
 * Date: Tue, 17 Dec 2013 15:38:31 +0000
 */

$conf['title'] = 'BioCatalogue';
$conf['start'] = 'home';
$conf['template'] = 'sidemenu';
$conf['basedir'] = '/wiki/';
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['subscribers'] = 1;
$conf['mailfrom'] = 'biocatalogue@mygrid.org.uk';
$conf['send404'] = 1;
$conf['plugin']['swiftmail']['smtp_host'] = 'smtp.gmail.com';
$conf['plugin']['swiftmail']['smtp_port'] = 465;
$conf['plugin']['swiftmail']['smtp_ssl'] = '4';
$conf['plugin']['swiftmail']['auth_user'] = 'biocatalogue@mygrid.org.uk';
$conf['plugin']['swiftmail']['auth_pass'] = 'pie5ahBo0aih';
$conf['plugin']['swiftmail']['debug'] = 1;
$conf['tpl']['sidemenu']['left_sidebar_content'] = 'main,user,group,namespace';
$conf['tpl']['sidemenu']['right_sidebar_content'] = 'main,user,group,namespace,index';
$conf['url'] = 'http://www.biocatalogue.org/wiki/';
$conf['openregister'] = '0';

// end auto-generated content
